name: Tulleworkflow

on:
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: read
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - uses: actions/checkout@v3
