name: Tulleworkflow

on:
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: read
    steps:
      - uses: actions/checkout@v3
      - uses: GitHubSecurityLab/action-permissions/advisor@v1
